### ISSUE TITLE
 Failure/Error: raise ArgumentError.new('must specify a key') if options[:key].to_s.empty?

### ISSUE THREAD

**Issue by namrin** [tinfoil/devise-two-factor#105]
How to pass key to shared spec 
RSpec.describe User, type: :model do 	
  it_behaves_like "two_factor_authenticatable"
end

1) User behaves like two_factor_authenticatable required_fields should have the attr_encrypted fields for otp_secret
     Failure/Error: raise ArgumentError.new('must specify a key') if options[:key].to_s.empty?
     
     ArgumentError:
       must specify a key
     Shared Example Group: "two_factor_authenticatable" called from ./spec/models/user_spec.rb:6

**Comment by dromazmj** [comment]
+1

**Comment by Foozie3Moons** [comment]
@dromazmj 

I was having this as well and realized it has to do with the rspec tests being unable to find the encryption key that you are using. I'm using devise inside of a rails engine, and had something like this:

```
# ./engines/my_engine/app/models/user.rb

otp_secret_encryption_key: Rails.application.secrets.otp_secret_encryption_key
```

Which won't work, since the engine itself does not have an application configuration file (the dummy app and the parent app do, though). So when the tests run, it will get to this line, try to find this secret, and returns nil because it can't find it. So to satisfy the tests, I just added `|| SecureRandom.hex(16)` to the end of this line and it seems to pass the tests.

```
otp_secret_encryption_key: Rails.application.secrets.otp_secret_encryption_key || SecureRandom.hex(16)
```

**Comment by dromazmj** [comment]
@Foozie3Moons 

I figured it out earlier today.  My problem was that I am using attr_encrypted with devise and I did not specify my database key for running in the test environment in the config/secrets.yml file.

`development:
      secret_key_base: ******************************************************************************
      db: *************************

test:
      secret_key_base: ******************************************************************************
      db: *************************
`

**Comment by Foozie3Moons** [comment]
Interesting, glad you figured it out!
