### ISSUE TITLE
OTPs issued by Google Authenticator don't match user.current_otp

### ISSUE THREAD

**Issue by whitethunder** [tinfoil/devise-two-factor#169]
I've probably done something wrong, but I can't seem to log in using 2FA on a new Rails 6 app using devise 4.7.1 and devise-two-factor 3.1.0. The codes generated by Google Authenticator are failing authentication, but the codes generated in a Rails console with `user.current_otp` are valid and I can log in with them.

I followed the instructions on https://github.com/tinfoil/devise-two-factor#enabling-two-factor-authentication to the letter. The provisioning URI generated is:

`otpauth://totp/Client%20Name:my@email.test?secret=ckd...bt7&issuer=Client+Name`

It adds to Google Authenticator just fine but the code generated there is always different than the user's `current_otp`. Any idea what I've done wrong? Thanks.

**Comment by QuinnWilton** [comment]
Hi @whitethunder! Just to double-check, is the time on the device you're running Google authenticator on synced with the time of your Rails server? 

This sort of issue is typically caused by clocks being out of sync with each other, so I want to rule that out before anything else :)

**Comment by whitethunder** [comment]
They're within a second of each other. I tried swapping out `devise-two-factor` for `two_factor_authentication` and it seems to work. Not sure what the difference is :confused:

**Comment by firstpromoter** [comment]
I'm getting the same issue. Do you know how this could happen?

**Comment by crysper** [comment]
Same here. That's weird. If you set it up again it works, but we can't ask users to set it up twice

**Comment by rylanb** [comment]
I'm seeing the same as @crysper is seeing. The first time a user tries to set this up the current code doesn't match what google authenticator is saying is their code. So they are locked out immediately. If they go back and rescan the QR code it works fine.

**Comment by crysper** [comment]
This happened numerous time since my last post and only on Google Authenticator .... what can it be?

**Comment by rylanb** [comment]
@crysper a good question. I looked back at the fixes and what happened w/ me was that users were hitting save an additional time and I hadn't prevented that issue.

I added: 
   
    # OTP is already on & 'Save' hit again. This will regenerate the code and cause lock out w/o this block.
    if @admin_user.otp_required_for_login && otp_required_for_login == '1'
      flash[:notice] = '2FA is already enabled! No need to click save again.'
      return redirect_to edit_two_factor_admin_admin_user_path(@admin_user.id)
    end

So that it would redirect back to the view instead of regenerating a new code (after they had already scanned one in Google Authenticator. 

The code before was: 
  
    if @admin_user.update(otp_required_for_login: otp_required_for_login)
      @admin_user.update!(otp_secret: AdminUser.generate_otp_secret)

And so, putting that guard block before fixed that up to prevent the extra `AdminUser.generate_otp_secret` call. Maybe you can find that flow happening in your app? I wonder if that came from a documented implementation here or from an article that could stand an update or a note added? 

Generally, make sure to not regenerate the OTP secret again through a UI/UX flow that enables the user to hit 'save' again.
