### ISSUE TITLE
How to enable using backup codes

### ISSUE THREAD

**Issue by connorshea** [tinfoil/devise-two-factor#56]
Should it be a separate page from the Authentication Code input page, or should the Authentication Code input page support backup codes? If the latter is what's intended, it isn't working for me. The README doesn't specify how we're supposed to do that.

**Comment by f3ndot** [comment]
You need only look at existing patterns and designs from other apps to determine what to do.

Some require you to click a "I don't have my phone" link or "login using backup codes" which keep the two keyspaces separate and probably allows for better monitoring of abuse. Other have a universal input field to which either an OTP or backup code will work.

I would prefer the former only because it's better UX to the user. You give them an opportunity to decide what to do with the leading question link, _"Don't have you phone?"_ vs. them guessing where a backup code goes. Plus it helps you decouple what keyspace is being bruteforced: OTP or backup codes. Combining them, in theory, could increase an attacker's chances of getting in.
